/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "user_define.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* Initialize LED (RED) */
void init_LED(void)
{
    /* Reset PC1 & PC2 in IOCR0*/
    PORT10_IOCR0 &= ~((0x1F) << PC1);
    PORT10_IOCR0 &= ~((0x1F) << PC2);

    /* Set PC1 & PC2 with push-pull(2b10000) */
    PORT10_IOCR0 |= ((0x10) << PC1);
    PORT10_IOCR0 |= ((0x10) << PC2);
}

/* Initialize Switch */
void init_Switch(void)
{
    /* Reset PC1 and PC0 in IOCR0*/
    PORT02_IOCR0 &= ~((0x1F) << PC1);
    PORT02_IOCR0 &= ~((0x1F) << PC0);

    /* Set PC1 and PC0 with pull-up(2b0xx10) */
    PORT02_IOCR0 |= ((0x2) << PC1);
    PORT02_IOCR0 |= ((0x2) << PC0);
}

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    init_LED(); // Initialize LED
    init_Switch(); // Initialize Switch

    volatile int cycle;

    int button_state[2] = { 0, 0 };
    int button_input[2] = { 0, 0 };
    int mode3 = 0;

    while (1) {
        if ((PORT02_IN & (1 << P0)) == 0 && (PORT02_IN & (1 << P1)) == 0) {
            for (cycle = 0; cycle < 1000000; cycle++) {
                if ((PORT02_IN & (1 << P0)) == 0 && (PORT02_IN & (1 << P1)) == 0)
                    mode3 = 1;
                else
                    mode3 = 0;
            }
        }

        if ((PORT02_IN & (1 << P1)) == 0) // Switch2 is pushed
            button_input[0] = 1;
        else
            button_input[0] = 0;

        if ((PORT02_IN & (1 << P0)) == 0) // Switch1 is pushed
            button_input[1] = 1;
        else
            button_input[1] = 0;

        if (mode3) {
            mode3 = 0;
            PORT10_OMR |= (1 << PS1); // LED RED on
            PORT10_OMR |= (1 << PCL2); // LED BLUE off
            for (int i = 0; i < 4; i++) {
                for (cycle = 0; cycle < 10000000; cycle++)
                    ; // Delay
                PORT10_OMR |= ((1 << PCL1) | (1 << PS1)); // Toggle LED RED
                PORT10_OMR |= ((1 << PCL2) | (1 << PS2)); // Toggle LED BLUE
            }
        } else {
            if (button_input[0] && button_state[0]) {
                PORT10_OMR |= ((1 << PCL1) | (1 << PS1)); // Toggle LED RED
                button_input[0] = 0;
                button_state[0] = 0;
            } else if (!button_input[0]) {
                button_state[0] = 1;
            }
            if (button_input[1] && button_state[1]) {
                PORT10_OMR |= ((1 << PCL2) | (1 << PS2)); // Toggle LED BLUE
                button_input[1] = 0;
                button_state[1] = 0;
            } else if (!button_input[1]) {
                button_state[1] = 1;
            }
        }
        for (int i = 0; i < 500000; i++)
            ;
    }

    return (1);
}
