/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "user_define.h"

void init_RGBLED(void);
void init_VADC(void);
void VADC_startConversion(void);
unsigned int VADC_readResult(void);

IfxCpu_syncEvent g_cpuSyncEvent = 0;

int avg;

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    unsigned int adcResult;

    /* Initialization */
    init_RGBLED(); // Initialize PORT
    init_VADC(); // Initialize VADC

    while (1) {
        int adc_arr[16] = {
            0,
        };

        for (int i = 0; i < 16; i++) {
            VADC_startConversion();
            adcResult = VADC_readResult();
            adc_arr[i] = adcResult;
        }

        /*
        printf("before sorting\n");
        for(int i = 0; i < 16; i++)
            printf("%d ", adc_arr[i]);
        printf("\n");
        */

        char swap;
        int temp;
        for (int i = 1; i < 16; i++) {
            swap = 'N';
            for (int j = 0; j < 16 - i; j++) {
                if (adc_arr[j] > adc_arr[j + 1]) {
                    temp = adc_arr[j];
                    adc_arr[j] = adc_arr[j + 1];
                    adc_arr[j + 1] = temp;
                }
            }
            if (swap == 'N')
                break;
        }

        /*
        printf("after sorting\n");
        for(int i = 0; i < 16; i++)
            printf("%d ", adc_arr[i]);
        printf("\n");
        */

        int sum = 0;
        for (int i = 4; i < 12; i++)
            sum += adc_arr[i];

        avg = sum / 8;
        // printf("avg: %d\n", sum / 8);

        for (volatile int cycle = 0; cycle < 10000000; cycle++)
            ; // Delay
    }
    return (1);
}

/* Initialize RGB LED */
void init_RGBLED(void)
{
    /* Reset IOCR0 bits */
    PORT02_IOCR4 &= ~((0x1F) << PC7);
    PORT10_IOCR4 &= ~((0x1F) << PC5);
    PORT10_IOCR0 &= ~((0x1F) << PC3);

    /* Set PC bits in IOCR0 with push-pull(2b10000) */
    PORT02_IOCR4 |= ((0x10) << PC7);
    PORT10_IOCR4 |= ((0x10) << PC5);
    PORT10_IOCR0 |= ((0x10) << PC3);
}

void init_VADC(void)
{
    /* VADC Enable */
    /* Password Access to unlock WDTCPU0CON0 */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0)
        ;

    /* Modify Access to clear ENDINIT bit */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0)
        ;

    VADC_CLC &= ~(1 << DISR); // Enable VADC Module

    /* Password Access to unlock WDTSCPU0CON0 */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0)
        ;

    /* Modify Access to clear ENDINIT bit */
    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while ((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0)
        ;

    while ((VADC_CLC & (1 << DISS)) != 0)
        ; // Wait until module is enabled

    VADC_G4ARBPR |= ((0x3) << PRIO0); // Highest Priority for Request Source 0
    VADC_G4ARBPR &= ~(1 << CSM0); // Conversion Start Mode : Wait-for-start mode
    VADC_G4ARBPR |= (1 << ASEN0); // Arbitration Source Input 0 Enable

    VADC_G4QMR0 &= ~((0x3) << ENGT); // Enable Conversion Requests
    VADC_G4QMR0 |= ((0x1) << ENGT);

    VADC_G4QMR0 |= (1 << FLUSH); // Clear all Queue Entries

    VADC_G4ARBCFG |= ((0x3) << ANONC); // Analog Converter : Normal Operation

    VADC_G4ICLASS0 &= ~((0x7) << CMS); // Group-specific Class 0
        // Conversion Mode : Standard Conversion (12-bit)

    /* VADC Group 4 Channel 7 Setting */
    VADC_G4CHCTR7 |= (1 << RESPOS); // Read Results Right-aligned
    VADC_G4CHCTR7 &= ~((0xF) << RESREG); // Store Result in Group Result Register G4RES1
    VADC_G4CHCTR7 |= (1 << RESREG);
    VADC_G4CHCTR7 &= ~((0x3) << ICLSEL); // Use Group-specific Class 0
}

void VADC_startConversion(void)
{
    /* No fill and Start Queue */
    VADC_G4QINR0 &= ~(0x1F); // Request Channel Number : 7
    VADC_G4QINR0 |= (0x07);

    VADC_G4QINR0 &= ~(1 << RF); // No fill : it is converted once

    VADC_G4QMR0 |= (1 << TREV); // Generate a Trigger Event
}

unsigned int VADC_readResult(void)
{
    unsigned int result;

    while ((VADC_G4RES1 & (1 << VF)) == 0)
        ; // Wait until New Result Available

    result = (VADC_G4RES1 & ((0xFFFF) << RESULT)); // Read Result

    return result;
}
